Домашнее задание 
# Тема: Действия с мультииндексами в датафреймах

In [1]:
import pandas as pd
import numpy as np

## Задание 1
Постройте датафрейм заполненный нулями так, как это показано в ячейке ниже. Первые две колонки являются мультииндексом. Для заполнения датафрейма нулями воспользуйтесь функцией zeros из библиотеки numpy

               Владивосток       Казань Новосибирск      
                    Кол-во Сумма  Сумма      Кол-во Сумма
Группа 1 Альфа         0.0   0.0    0.0         0.0   0.0
         Бета          0.0   0.0    0.0         0.0   0.0
Группа 2 Альфа         0.0   0.0    0.0         0.0   0.0
         Бета          0.0   0.0    0.0         0.0   0.0

In [4]:
df1_result = pd.DataFrame(
        np.zeros((4, 5)), 
        index=[['Группа 1', 'Группа 1', 'Группа 2', 'Группа 2',], ['Альфа', 'Бета', 'Альфа', 'Бета',]],
        columns=[['Владивосток', 'Владивосток', 'Казань', 'Новосибирск', 'Новосибирск',], ['Кол-во', 'Сумма', 'Сумма', 'Кол-во', 'Сумма']]
)
df1_result

               Владивосток       Казань Новосибирск
                    Кол-во Сумма  Сумма      Кол-во Сумма
Группа 1 Альфа         0.0   0.0    0.0         0.0   0.0
         Бета          0.0   0.0    0.0         0.0   0.0
Группа 2 Альфа         0.0   0.0    0.0         0.0   0.0
         Бета          0.0   0.0    0.0         0.0   0.0

Получившийся датафрейм сохраните в csv файл и загрузите на степик

In [5]:
df1_result.to_csv('df1_result.csv')

## Задание 2
Загрузите датафрейм из файла task5.csv. Поменяйте местами уровни так чтобы сначала шел тип парковки (платная/бесплатная), затем округ и район. Отсортируйте так чтобы сначала шли бесплатные парковки в алфавитном порядке по округу, а внутри округа в алфавитном порядке по району*. 

*Некоторые названия районов записаны наоборот: вместо район Нижегородский записано Нижегородский район. Из-за этого сортировка по алфавиту будет идти не совсем так, как вы ожидали. Оставим результат сортировки по алфавиту как есть (переносить слово район для корректной сортировки не будем).

In [2]:
df2_task = pd.read_csv('task5.csv', index_col=[0, 1, 2], header=[0, 1]) # не редактируйте ячейку

In [3]:
df2_task

                                                                        Capacity  \
                                                                           count
Восточный административный округ Нижегородский район         Бесплатная        1
                                 район Богородское           Бесплатная        2
                                                             Платная           1
                                 район Вешняки               Бесплатная        5
                                                             Платная           3
...                                                                          ...
Южный административный округ     район Чертаново Северное    Платная           2
                                 район Чертаново Центральное Бесплатная        7
                                                             Платная           3
                                 район Чертаново Южное       Бесплатная        9
                                                             Платная           4

                                                                             \
                                                                        sum
Восточный административный округ Нижегородский район         Бесплатная   6
                                 район Богородское           Бесплатная  14
                                                             Платная      8
                                 район Вешняки               Бесплатная  35
                                                             Платная     17
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная     20
                                 район Чертаново Центральное Бесплатная  68
                                                             Платная     21
                                 район Чертаново Южное       Бесплатная  86
                                                             Платная     36

                                                                        rating  \
                                                                           min
Восточный административный округ Нижегородский район         Бесплатная      8
                                 район Богородское           Бесплатная      8
                                                             Платная         0
                                 район Вешняки               Бесплатная      2
                                                             Платная         0
...                                                                        ...
Южный административный округ     район Чертаново Северное    Платная         2
                                 район Чертаново Центральное Бесплатная      0
                                                             Платная         3
                                 район Чертаново Южное       Бесплатная      3
                                                             Платная         0

                                                                             \
                                                                        max
Восточный административный округ Нижегородский район         Бесплатная   8
                                 район Богородское           Бесплатная  10
                                                             Платная      0
                                 район Вешняки               Бесплатная  10
                                                             Платная      9
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная      6
                                 район Чертаново Центральное Бесплатная   9
                                                             Платная      9
                                 район Чертаново Южное       Бесплатная  10
                                                             Платная      9


                                                                             mean
Восточный административный округ Нижегородский район         Бесплатная  8.000000
                                 район Богородское           Бесплатная  9.000000
                                                             Платная     0.000000
                                 район Вешняки               Бесплатная  6.800000
                                                             Платная     4.666667
...                                                                           ...
Южный административный округ     район Чертаново Северное    Платная     4.000000
                                 район Чертаново Центральное Бесплатная  3.571429
                                                             Платная     6.000000
                                 район Чертаново Южное       Бесплатная  6.666667
                                                             Платная     5.000000

[247 rows x 5 columns]

Обратите внимание, наш датафрейм немного усложнился: у мультииндекса строк пропали названия для уровней (добавлять их не стоит) и появился мультииндекс для колонок. Теперь в датафрейме содержится дополнительная информация о рейтинге парковки: маинимальное, максимальное и среднее значение

In [8]:
df2_result = df2_task.swaplevel(0, 2).swaplevel(1, 2).sort_index()
df2_result

                                                                         Capacity  \
                                                                            count
Бесплатная Восточный административный округ Нижегородский район                 1
                                            район Богородское                   2
                                            район Вешняки                       5
                                            район Восточное Измайлово           1
                                            район Гольяново                     2
...                                                                           ...
Платная    Южный административный округ     район Орехово-Борисово Южное       10
                                            район Царицыно                      4
                                            район Чертаново Северное            2
                                            район Чертаново Центральное         3
                                            район Чертаново Южное               4

                                                                              \
                                                                         sum
Бесплатная Восточный административный округ Нижегородский район            6
                                            район Богородское             14
                                            район Вешняки                 35
                                            район Восточное Измайлово      8
                                            район Гольяново                9
...                                                                       ..
Платная    Южный административный округ     район Орехово-Борисово Южное  85
                                            район Царицыно                38
                                            район Чертаново Северное      20
                                            район Чертаново Центральное   21
                                            район Чертаново Южное         36

                                                                         rating  \
                                                                            min
Бесплатная Восточный административный округ Нижегородский район               8
                                            район Богородское                 8
                                            район Вешняки                     2
                                            район Восточное Измайлово         6
                                            район Гольяново                   0
...                                                                         ...
Платная    Южный административный округ     район Орехово-Борисово Южное      0
                                            район Царицыно                    2
                                            район Чертаново Северное          2
                                            район Чертаново Центральное       3
                                            район Чертаново Южное             0

                                                                              \
                                                                         max
Бесплатная Восточный административный округ Нижегородский район            8
                                            район Богородское             10
                                            район Вешняки                 10
                                            район Восточное Измайлово      6
                                            район Гольяново               10
...                                                                       ..
Платная    Южный административный округ     район Орехово-Борисово Южное   7
                                            район Царицыно                10
                                            район Чертаново Северное       6
                                            район Чертаново Центральное    9
                                            район Чертаново Южное          9


                                                                         mean
Бесплатная Восточный административный округ Нижегородский район           8.0
                                            район Богородское             9.0
                                            район Вешняки                 6.8
                                            район Восточное Измайлово     6.0
                                            район Гольяново               5.0
...                                                                       ...
Платная    Южный административный округ     район Орехово-Борисово Южное  2.4
                                            район Царицыно                6.5
                                            район Чертаново Северное      4.0
                                            район Чертаново Центральное   6.0
                                            район Чертаново Южное         5.0

[247 rows x 5 columns]

Сохраните на степик только первые 27 записей датафрейма.

In [9]:
df2_result[:27].to_csv('df2_result.csv')

## Задание 3
Загрузите датафрейм из файла task5.csv. Из мультииндекса строк сбросьте уровень в котором содержится информация о типе парковки. Сохраните данные из этого уровня в отдельную колонку под названием `type`. Из целого датафрейма вырезаем только данные о рейтинге, сортируем записи по среднему рейтингу в порядке убывания и загружаем на степик ТОП-10 записей.

In [2]:
df3_task = pd.read_csv('task5.csv', index_col=[0, 1, 2], header=[0, 1]) # не редактируйте ячейку

In [3]:
df3_task

                                                                        Capacity  \
                                                                           count
Восточный административный округ Нижегородский район         Бесплатная        1
                                 район Богородское           Бесплатная        2
                                                             Платная           1
                                 район Вешняки               Бесплатная        5
                                                             Платная           3
...                                                                          ...
Южный административный округ     район Чертаново Северное    Платная           2
                                 район Чертаново Центральное Бесплатная        7
                                                             Платная           3
                                 район Чертаново Южное       Бесплатная        9
                                                             Платная           4

                                                                             \
                                                                        sum
Восточный административный округ Нижегородский район         Бесплатная   6
                                 район Богородское           Бесплатная  14
                                                             Платная      8
                                 район Вешняки               Бесплатная  35
                                                             Платная     17
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная     20
                                 район Чертаново Центральное Бесплатная  68
                                                             Платная     21
                                 район Чертаново Южное       Бесплатная  86
                                                             Платная     36

                                                                        rating  \
                                                                           min
Восточный административный округ Нижегородский район         Бесплатная      8
                                 район Богородское           Бесплатная      8
                                                             Платная         0
                                 район Вешняки               Бесплатная      2
                                                             Платная         0
...                                                                        ...
Южный административный округ     район Чертаново Северное    Платная         2
                                 район Чертаново Центральное Бесплатная      0
                                                             Платная         3
                                 район Чертаново Южное       Бесплатная      3
                                                             Платная         0

                                                                             \
                                                                        max
Восточный административный округ Нижегородский район         Бесплатная   8
                                 район Богородское           Бесплатная  10
                                                             Платная      0
                                 район Вешняки               Бесплатная  10
                                                             Платная      9
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная      6
                                 район Чертаново Центральное Бесплатная   9
                                                             Платная      9
                                 район Чертаново Южное       Бесплатная  10
                                                             Платная      9


                                                                             mean
Восточный административный округ Нижегородский район         Бесплатная  8.000000
                                 район Богородское           Бесплатная  9.000000
                                                             Платная     0.000000
                                 район Вешняки               Бесплатная  6.800000
                                                             Платная     4.666667
...                                                                           ...
Южный административный округ     район Чертаново Северное    Платная     4.000000
                                 район Чертаново Центральное Бесплатная  3.571429
                                                             Платная     6.000000
                                 район Чертаново Южное       Бесплатная  6.666667
                                                             Платная     5.000000

[247 rows x 5 columns]

In [26]:
df3_result = df3_task.loc[:, 'rating'].reset_index(level=-1).rename(columns={'level_2': 'type'}).sort_values('mean', ascending=False).head(10)
df3_result

                                                                  type  min  \
Юго-Восточный административный округ  район Некрасовка      Бесплатная   10
Зеленоградский административный округ район Силино             Платная   10
Северный административный округ       район Сокол              Платная   10
Западный административный округ       район Марьино            Платная   10
                                      район Филёвский Парк  Бесплатная   10
Юго-Восточный административный округ  район Печатники       Бесплатная    9
Западный административный округ       Можайский район       Бесплатная    9
                                      район Дорогомилово    Бесплатная    9
Юго-Восточный административный округ  Гагаринский район     Бесплатная    9
Новомосковский административный округ поселение Сосенское      Платная    9

                                                            max  mean
Юго-Восточный административный округ  район Некрасовка       10  10.0
Зеленоградский административный округ район Силино           10  10.0
Северный административный округ       район Сокол            10  10.0
Западный административный округ       район Марьино          10  10.0
                                      район Филёвский Парк   10  10.0
Юго-Восточный административный округ  район Печатники         9   9.0
Западный административный округ       Можайский район         9   9.0
                                      район Дорогомилово      9   9.0
Юго-Восточный административный округ  Гагаринский район       9   9.0
Новомосковский административный округ поселение Сосенское     9   9.0

Сохраните и отправьте файл на степик.

In [27]:
df3_result.to_csv('df3_result.csv')

## Задание 4 
В одном из прошлых заданий мы выбирали все районы восточного административного округа и искали где больше всего мест на бесплатных парковках. Загрузите датафрейм из файла task5.csv и попробуйте найти в каком округе больше всего парковок (и платных и бесплатных вместе). Учитывайте только те районы, где средний рейтинг парковок больше или равен 5

In [2]:
df4_task = pd.read_csv('task5.csv', index_col=[0, 1, 2], header=[0, 1]) # не редактируйте ячейку

In [7]:
df4_task.sample(3)

                                                                         Capacity  \
                                                                            count
Северо-Восточный административный округ Останкинский район    Бесплатная        6
Южный административный округ            район Чертаново Южное Бесплатная        9
Юго-Восточный административный округ    район Текстильщики    Платная           4

                                                                              \
                                                                         sum
Северо-Восточный административный округ Останкинский район    Бесплатная  40
Южный административный округ            район Чертаново Южное Бесплатная  86
Юго-Восточный административный округ    район Текстильщики    Платная     25

                                                                         rating  \
                                                                            min
Северо-Восточный административный округ Останкинский район    Бесплатная      0
Южный административный округ            район Чертаново Южное Бесплатная      3
Юго-Восточный административный округ    район Текстильщики    Платная         2

                                                                              \
                                                                         max
Северо-Восточный административный округ Останкинский район    Бесплатная  10
Южный административный округ            район Чертаново Южное Бесплатная  10
Юго-Восточный административный округ    район Текстильщики    Платная      9


                                                                              mean
Северо-Восточный административный округ Останкинский район    Бесплатная  5.333333
Южный административный округ            район Чертаново Южное Бесплатная  6.666667
Юго-Восточный административный округ    район Текстильщики    Платная     6.500000

In [52]:
df4_task\
    [df4_task[('rating', 'mean')] >= 5]\
    [('Capacity', 'count')]\
    .groupby(level=0)\
    .sum()\
    .idxmax()

'Северо-Восточный административный округ'

Правильный ответ выберите на степике

## Задание 5
Загрузите датафрейм из файла task5.csv. В этой задаче вы попробуете перейти от мультииндекса к обычному индексу с сохранением информации об уровнях. Сейчас на нулевом уровне колонки разбиваются на Capacity и rating, а на первом уровне Capacity и rating детализируются на count/sum и min/max/mean соответственно.  
Попытайтесь уйти от иерархии с сохранением информации о ней: сделайте обычный индекс с названием колонок:  
Capacity_count, Capacity_sum, rating_min, rating_max, rating_mean  

Не пытайтесь руками составить список и присвоить его т.к. на практике у вас может быть много колонок и руками перебирать будет долго. А еще можно что-то перепутать и тогда будет ошибка в последующих расчётах. Попробуйте перебрать значения мультииндекса в цикле и собрать тот самый список, который уже и присвоите обратно в датафрейм

In [2]:
df5_task = pd.read_csv('task5.csv', index_col=[0, 1, 2], header=[0, 1]) # не редактируйте ячейку

In [3]:
df5_task

                                                                        Capacity  \
                                                                           count
Восточный административный округ Нижегородский район         Бесплатная        1
                                 район Богородское           Бесплатная        2
                                                             Платная           1
                                 район Вешняки               Бесплатная        5
                                                             Платная           3
...                                                                          ...
Южный административный округ     район Чертаново Северное    Платная           2
                                 район Чертаново Центральное Бесплатная        7
                                                             Платная           3
                                 район Чертаново Южное       Бесплатная        9
                                                             Платная           4

                                                                             \
                                                                        sum
Восточный административный округ Нижегородский район         Бесплатная   6
                                 район Богородское           Бесплатная  14
                                                             Платная      8
                                 район Вешняки               Бесплатная  35
                                                             Платная     17
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная     20
                                 район Чертаново Центральное Бесплатная  68
                                                             Платная     21
                                 район Чертаново Южное       Бесплатная  86
                                                             Платная     36

                                                                        rating  \
                                                                           min
Восточный административный округ Нижегородский район         Бесплатная      8
                                 район Богородское           Бесплатная      8
                                                             Платная         0
                                 район Вешняки               Бесплатная      2
                                                             Платная         0
...                                                                        ...
Южный административный округ     район Чертаново Северное    Платная         2
                                 район Чертаново Центральное Бесплатная      0
                                                             Платная         3
                                 район Чертаново Южное       Бесплатная      3
                                                             Платная         0

                                                                             \
                                                                        max
Восточный административный округ Нижегородский район         Бесплатная   8
                                 район Богородское           Бесплатная  10
                                                             Платная      0
                                 район Вешняки               Бесплатная  10
                                                             Платная      9
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная      6
                                 район Чертаново Центральное Бесплатная   9
                                                             Платная      9
                                 район Чертаново Южное       Бесплатная  10
                                                             Платная      9


                                                                             mean
Восточный административный округ Нижегородский район         Бесплатная  8.000000
                                 район Богородское           Бесплатная  9.000000
                                                             Платная     0.000000
                                 район Вешняки               Бесплатная  6.800000
                                                             Платная     4.666667
...                                                                           ...
Южный административный округ     район Чертаново Северное    Платная     4.000000
                                 район Чертаново Центральное Бесплатная  3.571429
                                                             Платная     6.000000
                                 район Чертаново Южное       Бесплатная  6.666667
                                                             Платная     5.000000

[247 rows x 5 columns]

In [14]:
df5_result = df5_task.copy(deep=True)
df5_result.columns = df5_task.columns.to_frame().apply(lambda x: x[0] + '_' + x[1], axis=1).values
df5_result

                                                                         Capacity_count  \
Восточный административный округ Нижегородский район         Бесплатная               1
                                 район Богородское           Бесплатная               2
                                                             Платная                  1
                                 район Вешняки               Бесплатная               5
                                                             Платная                  3
...                                                                                 ...
Южный административный округ     район Чертаново Северное    Платная                  2
                                 район Чертаново Центральное Бесплатная               7
                                                             Платная                  3
                                 район Чертаново Южное       Бесплатная               9
                                                             Платная                  4

                                                                         Capacity_sum  \
Восточный административный округ Нижегородский район         Бесплатная             6
                                 район Богородское           Бесплатная            14
                                                             Платная                8
                                 район Вешняки               Бесплатная            35
                                                             Платная               17
...                                                                               ...
Южный административный округ     район Чертаново Северное    Платная               20
                                 район Чертаново Центральное Бесплатная            68
                                                             Платная               21
                                 район Чертаново Южное       Бесплатная            86
                                                             Платная               36

                                                                         rating_min  \
Восточный административный округ Нижегородский район         Бесплатная           8
                                 район Богородское           Бесплатная           8
                                                             Платная              0
                                 район Вешняки               Бесплатная           2
                                                             Платная              0
...                                                                             ...
Южный административный округ     район Чертаново Северное    Платная              2
                                 район Чертаново Центральное Бесплатная           0
                                                             Платная              3
                                 район Чертаново Южное       Бесплатная           3
                                                             Платная              0

                                                                         rating_max  \
Восточный административный округ Нижегородский район         Бесплатная           8
                                 район Богородское           Бесплатная          10
                                                             Платная              0
                                 район Вешняки               Бесплатная          10
                                                             Платная              9
...                                                                             ...
Южный административный округ     район Чертаново Северное    Платная              6
                                 район Чертаново Центральное Бесплатная           9
                                                             Платная              9
                                 район Чертаново Южное       Бесплатная          10
                                                             Платная              9

                                                                         rating_mean
Восточный административный округ Нижегородский район         Бесплатная     8.000000
                                 район Богородское           Бесплатная     9.000000
                                                             Платная        0.000000
                                 район Вешняки               Бесплатная     6.800000
                                                             Платная        4.666667
...                                                                              ...
Южный административный округ     район Чертаново Северное    Платная        4.000000
                                 район Чертаново Центральное Бесплатная     3.571429
                                                             Платная        6.000000
                                 район Чертаново Южное       Бесплатная     6.666667
                                                             Платная        5.000000

[247 rows x 5 columns]

Сохраните и отправьте файл на степик.

In [15]:
df5_result.to_csv('df5_result.csv')

## Задача 6
Загрузите данные из task5.csv. По всей Москве рассчитайте:
- Общее количество бесплатных парковок,
- Общее количество платных парковок,
- Общее количество мест на бесплатных парковках,
- Общее количество мест на платных парковках

Введите в поле с ответом получившиеся значения через пробел. В ответе должны быть целые числа
Пример: 10 12 90 110

In [2]:
df6_task = pd.read_csv('task5.csv', index_col=[0, 1, 2], header=[0, 1])

In [3]:
df6_task

                                                                        Capacity  \
                                                                           count
Восточный административный округ Нижегородский район         Бесплатная        1
                                 район Богородское           Бесплатная        2
                                                             Платная           1
                                 район Вешняки               Бесплатная        5
                                                             Платная           3
...                                                                          ...
Южный административный округ     район Чертаново Северное    Платная           2
                                 район Чертаново Центральное Бесплатная        7
                                                             Платная           3
                                 район Чертаново Южное       Бесплатная        9
                                                             Платная           4

                                                                             \
                                                                        sum
Восточный административный округ Нижегородский район         Бесплатная   6
                                 район Богородское           Бесплатная  14
                                                             Платная      8
                                 район Вешняки               Бесплатная  35
                                                             Платная     17
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная     20
                                 район Чертаново Центральное Бесплатная  68
                                                             Платная     21
                                 район Чертаново Южное       Бесплатная  86
                                                             Платная     36

                                                                        rating  \
                                                                           min
Восточный административный округ Нижегородский район         Бесплатная      8
                                 район Богородское           Бесплатная      8
                                                             Платная         0
                                 район Вешняки               Бесплатная      2
                                                             Платная         0
...                                                                        ...
Южный административный округ     район Чертаново Северное    Платная         2
                                 район Чертаново Центральное Бесплатная      0
                                                             Платная         3
                                 район Чертаново Южное       Бесплатная      3
                                                             Платная         0

                                                                             \
                                                                        max
Восточный административный округ Нижегородский район         Бесплатная   8
                                 район Богородское           Бесплатная  10
                                                             Платная      0
                                 район Вешняки               Бесплатная  10
                                                             Платная      9
...                                                                      ..
Южный административный округ     район Чертаново Северное    Платная      6
                                 район Чертаново Центральное Бесплатная   9
                                                             Платная      9
                                 район Чертаново Южное       Бесплатная  10
                                                             Платная      9


                                                                             mean
Восточный административный округ Нижегородский район         Бесплатная  8.000000
                                 район Богородское           Бесплатная  9.000000
                                                             Платная     0.000000
                                 район Вешняки               Бесплатная  6.800000
                                                             Платная     4.666667
...                                                                           ...
Южный административный округ     район Чертаново Северное    Платная     4.000000
                                 район Чертаново Центральное Бесплатная  3.571429
                                                             Платная     6.000000
                                 район Чертаново Южное       Бесплатная  6.666667
                                                             Платная     5.000000

[247 rows x 5 columns]

In [6]:
df = df6_task.reset_index().rename(columns={'level_0': 'okrug', 'level_1': 'rajon', 'level_2': 'type'})

In [9]:
df[df.type == 'Бесплатная'][('Capacity', 'count')].sum()

518

In [11]:
df[df.type == 'Платная'][('Capacity', 'count')].sum()

529

In [12]:
df[df.type == 'Бесплатная'][('Capacity', 'sum')].sum()

3455

In [13]:
df[df.type == 'Платная'][('Capacity', 'sum')].sum()

3642

In [17]:
df6_task['Capacity'].sum(level=2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  """Entry point for launching an IPython kernel.

            count   sum
Бесплатная    518  3455
Платная       529  3642

### Пробы

In [3]:
data = np.array([[50000, 16, 50000, 16],
                 [45000, 15, 45000, 15,],
                 [40000, 14, 40000, 14],
                 [55000, 15, 55000, 15],
                 [47000, 13, 47000, 13],
                 [45000, 12, 45000, 12],
                 [52000, 17, 52000, 17],
                 [43000, 15, 43000, 15],
                 [41000, 13, 41000, 13]])

index = [['Тестирование', 'Тестирование', 'Тестирование', 'Разработка', 'Разработка', 'Разработка', 'Аналитика', 'Аналитика', 'Аналитика'], ['Начальник', 'Эксперт', 'Специалист', 'Начальник', 'Эксперт', 'Специалист', 'Начальник', 'Эксперт', 'Специалист']]

columns = [['Москва', 'Москва', 'Казань', 'Казань'], ['Зарплата', 'Уровень', 'Зарплата', 'Уровень']]

df = pd.DataFrame(data, index=index, columns=columns)

In [4]:
df

                          Москва           Казань
                        Зарплата Уровень Зарплата Уровень
Тестирование Начальник     50000      16    50000      16
             Эксперт       45000      15    45000      15
             Специалист    40000      14    40000      14
Разработка   Начальник     55000      15    55000      15
             Эксперт       47000      13    47000      13
             Специалист    45000      12    45000      12
Аналитика    Начальник     52000      17    52000      17
             Эксперт       43000      15    43000      15
             Специалист    41000      13    41000      13

In [8]:
df.index.names = ['Отдел', 'Должность']
df.columns.names = ['Город', 'Показатель']

In [9]:
df

Город                     Москва           Казань
Показатель              Зарплата Уровень Зарплата Уровень
Отдел        Должность
Тестирование Начальник     50000      16    50000      16
             Эксперт       45000      15    45000      15
             Специалист    40000      14    40000      14
Разработка   Начальник     55000      15    55000      15
             Эксперт       47000      13    47000      13
             Специалист    45000      12    45000      12
Аналитика    Начальник     52000      17    52000      17
             Эксперт       43000      15    43000      15
             Специалист    41000      13    41000      13